#!/bin/bash
# alarm.sh
# Usage: ./alarm.sh "$TIME $CUSTOM_MESSAGE"
#
# Requires espeak TTS
#
# Written by William Chung (wiiliamchung360@gmail.com)
#

date=$( echo $1 | cut -d' ' -f1 )
c_message=$( echo $1 | cut -d' ' -f2- | sed -e 's/ /_/g' )

if [ -z $1 ]; then
  printf "What time are you setting this alarm for? "
  read date
  printf "Do you want to use a custom message? [y/N] "
  read c_message_yn
  if [ $c_message_yn = "y" ] || [ $c_message_yn = "Y" ]; then
    printf "What would you want me to say? "
    read c_message
  fi
elif [ $c_message = $date ]; then
  echo "Okay! Will ring you on $(date --date="$date")."
  delay=$( echo $(( $(date --date="$date" +%s) - $(date +%s) )) )
  #echo $delay
  sleep $delay
  echo "Wake up!"
  while true; do
    espeak "wake up" &>/dev/null
    espeak "Wake up" &>/dev/null
    espeak "Wake up" &>/dev/null
    espeak "it is now" &>/dev/null
    h=$(date +%_I)
    espeak $h &>/dev/null
    m=$(date +%M)
    espeak $m &>/dev/null
    sleep 1
  done
fi

echo "Okay! Will ring you on $(date --date="$date")."
delay=$( echo $(( $(date --date="$date" +%s) - $(date +%s) )) )
#echo $delay
sleep $delay
echo "Wake up!"
while true; do
  espeak $c_message &>/dev/null
#  echo $c_message
  sleep 1
done
